### ISSUE TITLE
Can you not return objects via to runTask?

### ISSUE THREAD

**Issue by VeNoMouS** [jasnell/piscina#102]
Just confirming you cannot return Objects to runTask? 

if this is the case... seems very innocent to convert to json then parse on the other side...

**Comment by jasnell** [comment]
You can. runTask returns a Promise that resolves with the return value of the worker function.

so... if worker worker is:

```js
module.exports = async () => return { a: 1, b: 2 };
```

then... `const ret = await piscina.runTask()` will return the object.

**Comment by VeNoMouS** [comment]
I get a ` UnhandledPromiseRejectionWarning: DataCloneError: [object Object] could not be cloned.` error ...

off `piscina/dist/src/worker.js` line 175

**Comment by jasnell** [comment]
That can happen if any of the values in your object can't be cloned. What kind of values do you have in there?

**Comment by VeNoMouS** [comment]
nested object of strings and binary

**Comment by jasnell** [comment]
Without more detail there's not much we can do here. The objects transfered need to work with the structured clone algorithm or transferring will fail. There's nothing we can do in piscina to influence that as the requirements are set by node and v8
