### ISSUE TITLE
How to broadcast a message to all workers?

### ISSUE THREAD

**Issue by ronag** [jasnell/piscina#104]
I need a way to be able to send/publish/broadcast a message to all workers. Is this possible?

**Comment by jasnell** [comment]
With the new BroadcastChannel API in core yes, but it can be a bit tricky. There are timing issues around the lifecycle of a worker that can make it... difficult. Without using BroadcastChannel, there's no simple way of doing it -- you have to manage a MessagePort pair for every worker.

**Comment by jdmarshall** [comment]
Would you not hook into the WorkerInfo and post a message to each worker? Wouldn't that be simpler?
