### ISSUE TITLE
Crash on startup, no error given

### ISSUE THREAD

**Issue by shockdevv** [jasnell/piscina#105]
I'm using typescript, __dirname is not defined, so I'm resolving my path manually. 

`
this.workerPool = new Piscina({
            filename: path.resolve("test/worker", 'worker.js'),
            maxThreads: 2
});
`

Doesn't go past that.

**Comment by jasnell** [comment]
Are you able to provide a full script I can use to test a repro?

**Comment by shockdevv** [comment]
> Are you able to provide a full script I can use to test a repro?

We may have a bit of a problem: I'm using a multiplayer framework for GTA:V named alt:V which allows players to play on custom servers. Node js is fully supported, and my entire script is split into modules. Thing is as soon as I try to import my worker file (I have a single file which imports all files that are being used by my script), a _module is not defined_ error shows up. 

There's also another error you should probably be aware of. There you go and thanks in advance.
https://i.imgur.com/Mu5MGNn.png

`
this.workerPool = new Piscina({
            filename: path.resolve("resources/core/server/systems", 'streamer_worker.js'),
            maxThreads: 2
});
`

**Comment by jasnell** [comment]
Does not appear to be an issue in Piscina itself.
