### ISSUE TITLE
Node silently exits with code 0, no error, when using a specific string for String.includes inside worker

### ISSUE THREAD

**Issue by RoyHP** [jasnell/piscina#107]
Hey jasnell,

Node silently exits with code 0, no error, when using a specific string for String.includes inside worker. This happens during my call to await Promise.all(worker_promises) where worker_promises is an array of Piscina runTask() promises.

If you change it to a different string and run, it will exit normally producing full output.

I can give you my script to test with, but the problem is that it's designed to parse log file data from DDoS attacks (to count occurrences of requests matching certain patterns) and the dataset causing the issue is about 20GiB (1,186 gzipped log files). I can send it to you if you're okay with this.

Here are the two relevant sections of code and the output when it works:
<img width="1382" alt="Screen Shot 2021-02-10 at 6 08 44 PM" src="https://user-images.githubusercontent.com/1066439/107584969-5c89cd00-6bcb-11eb-84ae-ab3750c3e508.png">
<img width="203" alt="Screen Shot 2021-02-10 at 6 10 53 PM" src="https://user-images.githubusercontent.com/1066439/107584973-5e539080-6bcb-11eb-90d9-28c633a80794.png">

Here are the two relevant sections of code and the output when it silently fails:
<img width="140" alt="Screen Shot 2021-02-10 at 6 01 27 PM" src="https://user-images.githubusercontent.com/1066439/107584579-b50c9a80-6bca-11eb-83b3-317964eeedad.png">
<img width="1395" alt="Screen Shot 2021-02-10 at 6 02 02 PM" src="https://user-images.githubusercontent.com/1066439/107584600-be960280-6bca-11eb-960f-adf8fd7928cf.png">

The dataset remains the same between runs and there are no other code changes.

I'm on node v14.15.5, macOS 11.2 x86

**Comment by RoyHP** [comment]
Also it fails the same way on v14.15.4. I noticed the stream/zlib fix in https://github.com/nodejs/node/pull/36618 and wondered if it was related. Also fails in v12.20.1.

**Comment by RoyHP** [comment]
Note, it doesn't fail immediately but rather after processing a few hundred files.

**Comment by RoyHP** [comment]
So I found that it works if I comment out two console.log()'s that were trying to log a variable that doesn't exist... though it never gave me any errors about it.
<img width="588" alt="Screen Shot 2021-02-10 at 7 55 12 PM" src="https://user-images.githubusercontent.com/1066439/107592079-05d7bf80-6bda-11eb-87aa-1511e1d23938.png">

Could this console.log() have been somehow killing the worker threads and eventually it just stops and exits with 0 without continuing execution in main.js?

I apologize, it's just a quick and dirty script to get some insight into data.

**Comment by mcollina** [comment]
I'm glad you solved your own problem!

**Comment by imcuttle** [comment]
emmm how to resolve it?
