### ISSUE TITLE
Feature request: Worker initiated messages send to parent

### ISSUE THREAD

**Issue by mchen6** [jasnell/piscina#112]
Hi, Thanks for the great software!

I'm wondering if Piscina could add support to allow workers actively sending messages to parent main thread, with or without waiting for parent's acknowledgement. This feature may greatly improve the use case when we need to:

1) Send customized status updates from worker to main thread
2) Look up resources which only exist in main thread
3) Delegate I/O centric logic, or connection managements, e.g. DB connection pools to main thread to avoid excessive network connections in many workers
4) Allow call another worker from the context of current worker, and etc.

For example we could have below code runs in the context of worker threads:

const { callParent, sendMessageToParent } = require('piscina');

(async function () {
    const result = await callParent({ a: 4, b: 6 });  // child send message to parent
    console.log(result);  // waiting for parent acknowledges worker with the result
    //or without having to wait for parent's ack:
    sendMessageToParent({ a: 4, b: 6 })
})();

And in the context of main thread:
const Piscina = require('piscina');

const piscina = new Piscina({
    filename: path.resolve(__dirname, 'worker.js')
});

piscina.on('childmessage', (data) => {
    ...
});

**Comment by jasnell** [comment]
This is already possible using `MessagePort`. Take a look at the Progress example https://github.com/piscinajs/piscina/tree/current/examples/progress. The spawning thread has to create the MessagePort through which the worker will communicate, but once done, the Worker can send messages back as much as it would like. Newer Node.js versions also have access to `BroadcastChannel`, which can be used to send one-to-many message broadcasts.
