### ISSUE TITLE
Feature: Dynamic scaling of minimum worker count

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#117]
Currently the minimum number of workers is fixed at piscina start, with the minimum maintained at any given time. In discussion the idea of a dynamically scaled minimum based on the queue pressure was suggested. Essentially, rather than scale up one new worker at a time as needed when a new task is completed, automatically start launching N new workers (up to max worker count) while tasks are being added to the queue, where the minimum is dynamically calculated as a factor of the pending queue size.

Whether this would have a measurable performance improvement or not remains to be determined.

**Comment by addaleax** [comment]
I think this would be useful only in *very* specific situations, where you *know* that the scheduling of one task implies that another, independent task will always be scheduled soon (but not immediately) afterwards. That seems like a pretty uncommon scenario.
