### ISSUE TITLE
how to know if all the thread is initialized?

### ISSUE THREAD

**Issue by meixg** [jasnell/piscina#120]
we can do some initial work before actually do some task:

```js
async function initialize() {
  await someAsyncInitializationActivity();
  return ({ a, b }) => a + b;
}

module.exports = initialize();
```

if the minThreads is set, piscina will create threads automatically  when `new Piscina()` .

but **how to make sure all the thread is initialized before calling `runTask`**?

use case:
lots of node process, need make sure one process's all threads is initialized before handle user request, otherwise the user request may get overtime error.

is there a 'ready' event?

**Comment by jasnell** [comment]
Worker threads in general have a `ready` event, yes. In Piscina, `runTask()` will not attempt to dispatch tasks to workers until after the worker signal they are ready.

**Comment by meixg** [comment]
> Worker threads in general have a `ready` event, yes. In Piscina, `runTask()` will not attempt to dispatch tasks to workers until after the worker signal they are ready.

I know that Piscina use worker's `ready` event inside, 
but maybe we need a `ready` event from Piscina.

start server -> wait all threads ready (use minThreads) -> server listen()

**Comment by jasnell** [comment]
Sorry for the later response. I'm not sure a ready event for piscina is useful, to be honest. Tasks are queued until there's a worker available and there's really no reason an application should have to wait to use the worker pool. Can you expand a bit on the use case?

**Comment by meixg** [comment]
When using on a server, the first few response will be too slow.
this happens especially when we have a big service, and the server restarts a lot per day (because of code iteration).
if we have a ready event, we can make some server restart first，wait ready，then restart others.

anyway, this maybe a extreme case.

I found a trick way to do this:

```javascript
async function initThread() {
    let threadNum = 10;
    let tasks = [];
    while (threadNum--) {
        // just init, thread can use `isWarmup`
        tasks.push(piscina.runTask({ isWarmup: true }));
    }
    await Promise.all(tasks);
}
```

**Comment by metcoder95** [comment]
Hey! Kind of late to the party but I believe the use case is interesting.
You want to do a warm-up of the threads, so they are ready beforehand (e.g. warm it up before starting to receive requests, similar to warming up the cache).

I agree with @jasnell that a `ready` might not be useful, but we already have `minThreads` at hand that can be used as a baseline, and Piscina ensures those minimum workers are available before starting processing tasks.
