### ISSUE TITLE
worker graceful shutdown

### ISSUE THREAD

**Issue by mashy-ma** [jasnell/piscina#121]
how can i handle graceful shutdown (connections and something like this ... ) of worker before terminate.
in case of destroy or no more threads ?

**Comment by mashy-ma** [comment]
i'm still waiting for your response....

**Comment by jasnell** [comment]
Currently, there is no reliable graceful shutdown option for a thread. The pool can terminate/destroy a thread abruptly, in which case no notification is sent to the worker and no additional javascript will be invoked in the worker. /cc @addaleax in case she has more context on the limitation here
