### ISSUE TITLE
Reusable worker pool

### ISSUE THREAD

**Issue by rubiin** [jasnell/piscina#123]
Hello, I am staring using this library. I am trying to create a pool of workers then assign them jobs dynamically so as to reuse the same pool of workers. How can i achieve this?

**Comment by jasnell** [comment]
Assuming that what you mean is that each job may have a different implementation, you can pass the path to the worker as an option in the [`piscina.runTask()`](https://github.com/piscinajs/piscina#method-runtasktask-transferlist-filename-abortsignal). Take a look at the [multiple-workers example](https://github.com/piscinajs/piscina/tree/current/examples/multiple-workers) for an illustration.

**Comment by rubiin** [comment]
does the function to execute has to be default import

**Comment by jasnell** [comment]
Yes, at least for now. I plan to revisit some of the options there to make it more flexible later.

**Comment by jasnell** [comment]
Just landed a change that allows multiple named worker exports from a single file. Will come out in a release soon

**Comment by rubiin** [comment]
> Just landed a change that allows multiple named worker exports from a single file. Will come out in a release soon

aye aye
