### ISSUE TITLE
Add `needDrain` property

### ISSUE THREAD

**Issue by ronag** [jasnell/piscina#126]
The current way to determine whether a pool needs a drain event before queueing more tasks is a little awkward. Can we add a `needDrain` proprerty?

```js
if (pool.needDrain) {
  await EE.once(pool, 'drain')
}
pool.runTask()
```

**Comment by ronag** [comment]
When does `'drain'` actually get emitted? Is it when the queue is empty or when the queue.size < queue.capacity?

**Comment by jasnell** [comment]
Currently when the queue is empty. The plan has been to go back and revisit that but haven't been able to get to it yet.

**Comment by ronag** [comment]
That’s doesn’t sound optimal.

**Comment by jasnell** [comment]
Yeah, it's not the most optimal approach but I haven't really had the opportunity to go back and figure out a more optimal strategy.

**Comment by metcoder95** [comment]
Which should be the optimal approach?

**Comment by metcoder95** [comment]
Hey @ronag, I'm planning to revisit this, do you have any suggestion for an optimal approach?

**Comment by ronag** [comment]
Not really. But I do think https://github.com/piscinajs/piscina/issues/348 is a duplicate of this.

**Comment by metcoder95** [comment]
I believe that we can have two action paths here:

1.  We can maybe start by adjusting the `drain` method to be triggered once as soon as the `queue.size < queue.capacity`, in that way we enable continuing work as soon as there is spare capacity to schedule more tasks (this will translate into a major, so we will need to point to `next` branch for this one)
2. Adding the `needsDrain`can be used as soon as the `maxQueue` has been reached. That should cover the requirement to understand when the pool needs to be waited for being drained until schedule a new task
