### ISSUE TITLE
Fixing coverage for ESM

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#129]
Just leaving this as a todo. Upgrading tap and typescript and updating the ESM settings broke some of the coverage reporting. Looks like an issue in tap as I've been able to verify that the areas reported as uncovered are actually being tested.

**Comment by mcollina** [comment]
The following works for me.

```sh
tap --node-arg='--no-warnings' --node-arg='--experimental-loader' --node-arg='@istanbuljs/esm-loader-hook' test/*test.js
```

**Comment by jasnell** [comment]
That doesn't appear to work in combination with the `--ts` option and `ts-node`
