### ISSUE TITLE
Discuss: Streams in and Streams out

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#13]
@mcollina @addaleax ... in looking through the possibility of using the worker pool for server side rendering, one of the difficulties is going to be the fact that existing SSR mechanisms (e.g. nextjs when using fastify-nextjs) require the ability to work directly with the request and response objects as streams (e.g. `app.render(req.raw, reply.res, '/hello', req.query, {})`). Within the worker thread, we do not have direct access to these streams, nor do we have access to the global nextjs application. The best we'd be able to do is create each worker such that it has it's own distinct image of the nextjs application without any streaming of the actual rendered data. That is obviously not ideal... 

We should try to find a way of enabling streaming data into and out of a task. We can likely use the worker threads already wrapped process.stdin and process.stdout so long as the concurrency of each worker is exactly 1 task at a time.

**Comment by mcollina** [comment]
Streaming SSR does not increase req/s, and it is not our less useless. We should just take the req, pass it down and get the output. Check out http://npm.im/light-my-request, it can be useful for mocking.

(We can also do a check with bare React)

**Comment by addaleax** [comment]
@jasnell How much would it actually help to have streams available for this? Would you still need to replicate a sizable amount of the app’s state, or would it really be enough to allow streams in & out?

**Comment by jasnell** [comment]
The short answer is: I don't know yet :)

**Comment by jasnell** [comment]
I've been playing around with a few scenarios on this and really can't find one that makes sense. Given that workers may be reused, it's just going to be overly complicated for little benefit.
