### ISSUE TITLE
Please add a changelog.md

### ISSUE THREAD

**Issue by Prinzhorn** [jasnell/piscina#131]
Or at least provide useful release notes in GitHub releases. I'm currently trying to figure out what breaking changes 3.0.0 brought and reading through every commit after 2.2.0 isn't fun.

I personally very much prefer a changelog.md over having the information only in the GitHub releases. The user experience of ctrl+f and skimming though a single markdown file is far superior than clicking through on GitHub (pagination...). And having the changelog locally inside the repo is also a plus.

**Comment by jasnell** [comment]
Will do so moving forward. 3.0.0 was major because we dropped support for Node.js 10

**Comment by rubiin** [comment]
> Will do so moving forward. 3.0.0 was major because we dropped support for Node.js 10

also any new features and fixes

**Comment by jasnell** [comment]
btw, there is a changelog at the end of the README.md ... for the 3.1.0 release I just did I added links to the new commits.

**Comment by Prinzhorn** [comment]
> btw, there is a changelog at the end of the README.md

Ooof, thanks! I was just "ctrl+f"ing for "changelog" and it hadn't crossed my mind to scroll all the way down there.

**Comment by jasnell** [comment]
No worries! I often forget that it's there also!! 🤣

**Comment by metcoder95** [comment]
Done since version `v4.2.0`
