### ISSUE TITLE
Add a typescript example

### ISSUE THREAD

**Issue by rubiin** [jasnell/piscina#134]
Please add a simple typescript example with a separate worker file.

**Comment by StarpTech** [comment]
Did you see https://github.com/piscinajs/piscina/tree/current/examples/typescript ?

**Comment by rubiin** [comment]
Its a simple example and does not cover many stuff. I also got an error on imports

**Comment by StarpTech** [comment]
> Its a simple example and does not cover many stuff

Could you be more specific?

> I also got an error on imports

Would you prepare a PR to fix this?

**Comment by rubiin** [comment]
you can see this https://github.com/piscinajs/piscina/issues/125
