### ISSUE TITLE
How to create Piscina instance by passing function instead of filename

### ISSUE THREAD

**Issue by alex-uw** [jasnell/piscina#140]
I'd like to have flexibility to pass arbitrary worker function, not a worker file name
Is this possible?
thanks

**Comment by jasnell** [comment]
No, that's not currently possible. We're limited here by how Node.js worker threads are loaded and those do not currently support initialization by passing a function.

**Comment by uzair004** [comment]
> No, that's not currently possible. We're limited here by how Node.js worker threads are loaded and those do not currently support initialization by passing a function.

Yes that's true, But this feature is available in [workerpool library](https://github.com/josdejong/workerpool)

**Comment by yvele** [comment]
> Yes that's true, But this feature is available in [workerpool library](https://github.com/josdejong/workerpool)

[workerpool](https://github.com/josdejong/workerpool) implements a [basic function serialization/deserialization](https://github.com/josdejong/workerpool/blob/28369c8be12c92f731a9a849aa79656d3b64abc0/src/worker.js#L93-L102) using `new Function` (kind of eval).

This looks handy at first glance but you will rapidly hit limitations:
 - https://github.com/josdejong/workerpool/issues/178#issuecomment-703083782
 - https://github.com/josdejong/workerpool/issues/189
 - etc..

And the real solution is to use a bundler (Webpack, rollup..)

Note that TC39 is working on a proposal regarding sharing functions and code to workers: https://github.com/tc39/proposal-js-module-blocks 👍
