### ISSUE TITLE
Usage with `ts-node-dev`

### ISSUE THREAD

**Issue by jackHedaya** [jasnell/piscina#143]
Hey there!

I'm encountering an issue when using `piscina` with `ts-node-dev`. Whenever I try to use `piscina` in a different worker file, I get

```
[ERROR] 10:45:27 Error: Cannot find module '/.../src/worker' imported from /.../src/worker.js
Did you mean to import /.../src/worker.ts?
```

However, when I change to `worker.ts`, I get

```
[ERROR] 10:47:05 TypeError: Unknown file extension ".ts" for /.../src/worker.ts
```

My `tsconfig.json` already includes `esModuleInterop`, which I know was the root of some other reported issues.

Thank you for this awesome library and the help!

**Comment by jasnell** [comment]
@addaleax ... any suggestions?

**Comment by rubiin** [comment]
share repo

**Comment by jackHedaya** [comment]
@rublin Unfortunately, I'm unable to show a repo because its a company project but this is the gist of what's happening:

**File Structure**

```
+ src
     -app.ts
     -worker.ts
```

and then in app.ts

```ts
const piscina = new Piscina({
  filename: path.resolve(__dirname, './worker.js'), // This is what I was attempting to change
})

piscina
      .run(
        { ...data },
        { name: 'fnName' }
      )
      .then((x) => console.log(`Successfully ran`))
```

**Comment by excal1bu7** [comment]
bump

**Comment by rogerthoang** [comment]
same issue here. seems like a common issue. theres at least 3 related issues open for this.

**Comment by arthurfiorette** [comment]
Hey guys, supporting various bundling plataforms seems out of scope. Y'all can fix it by (just for the "main thread file") using the same file to create the piscina instance and exporting your worker functions. This way you can use `__filename` as the filename option and all bundlers and runtime transpilers supports it.

**Comment by metcoder95** [comment]
Another option is to pass the `__dirname` or the `process.cwd()` output as argument to the worker and do some proper discovery based on that
