### ISSUE TITLE
possible to update array in worker?

### ISSUE THREAD

**Issue by it-harrison** [jasnell/piscina#144]
If I have something like:
```
//main.js
const piscina = new Piscina({
  filename: path.resolve(__dirname, 'process-file.js'),
});

const converted = [];
await Promise.allSettled(
  myFileList.map((file) => {
    return piscina.runTask(file, converted);
  })
);

console.log(converted)
```
And inside the file I pass to the `Piscina` constructor I have some code like:
```
//inside process-file.js
if(someCheckisTrue) {
   converted.push(file);
}
```
In `main.js`  the array logged to the console is always empty, even when I know that `someCheckIsTrue` = `True`. 

Is it possible to pass a reference to an array to the process that Piscina spawns? Or am I missing something?

**Comment by jasnell** [comment]
No, that's not possible. The values are passed as a copy. You'll need to return the modified array to the main thread.
