### ISSUE TITLE
Trouble understanding docs for perf (`maxQueue`, file IO)

### ISSUE THREAD

**Issue by NickHeiner** [jasnell/piscina#145]
I'm making [a codemod runner](https://github.com/NickHeiner/jscodemod/) that uses Piscina. The logic currently blasts thousands of files onto the queue at once:

```js
function transformFiles() {
  const piscina = new Piscina({filename: require.resolve('./worker')});
  return Promise.all(inputFiles.map(inputFile => piscina.runTask(inputFile)));
}
```

Sometimes, Piscina seems to take a long time to start. Specifically, I see a bunch of workers starting, before any of them actually start executing. The first few tasks take a relatively long time to complete, and then, tasks start completing quickly.

I wonder if it's because I'm filling the queue too aggressively. (My other thought is that `worker` loads too much JS when it starts up, so doing it many times is slow.)

Is the solution to this to set a lower `maxQueue` (like `'auto')`, and then manage how often I `runTask`? Why does the queue size impact Piscina performance? I would expect it's just a list of tasks, and whether it's maintained in or outside of Piscina wouldn't make a difference. But clearly I'm missing something. :smile:

Separately, the docs note that:

> This means that there will be little performance impact on moving such async operations into a Piscina worker (see examples/scrypt for example).

Does this mean that I should actively avoid doing IO in a worker? My codemod runner currently passes a file name to each worker, then that worker reads that file contents. I could instead read all file contents in the main thread. Would that be better?

Thanks!

**Comment by jasnell** [comment]
That very well could be it. Think of each Worker as essentially it's own Node.js instance. Each has it's own heap, each has to load, parse, and initialize the javascript on it's own, so you'll pay the start up cost for each worker. Depending on the number of workers you're starting and the number of cores you have available, you can see some contention if those are all trying to start at once. I've thought about implementing a staggered-start algorithm that prevents minThreads from initializing all at once but haven't been able to get around to it. What I would try is implementing a cold-start warm up, initialize a smaller number of threads with a smaller number of initial tasks, then ramp up.

With regards to the i/o question... it's not so much that you should avoid doing i/o in the worker as much as it is you won't see any performance benefit in doing so. Also keep in mind that every worker uses the same libuv thread pool that only has 4 threads by default. You can bottleneck things if you have lots of worker threads using a small number of libuv threads, all contending for cpu time. If you're going to be doing i/o in your workers, make sure you take your libuv thread pool into consideration. In general, we've found it ideal to keep i/o isolated to the main thread with compute in the workers, tho keep in mind that you will pay a performance cost using postMessage to get that data over to the worker.

@addaleax might have some other suggestions tho.

**Comment by NickHeiner** [comment]
Ok, thanks for that.

The API doesn't let me actually change params like `minThreads`, `maxThreads` etc after the pool is created, right? So I could just throttle the initial calls to `runTask` and see if that helps any?

Also, the docs say:

> When the maxQueue option is set, once the Piscina queue is full, no additional tasks may be submitted until the queue size falls below the limit.

What happens when the queue is full and tasks are submitted? A thrown error? Tasks are silently dropped?

**Comment by jasnell** [comment]
An error should be thrown

**Comment by metcoder95** [comment]
@NickHeiner is this still valid or can it be closed?

**Comment by NickHeiner** [comment]
I think the questions are still valid. :) But if no one else had the same question in the intervening years, it seems fine to close.

**Comment by metcoder95** [comment]
Let's close it for now and re-open it if someone faces the same issue, or open a freshly one. Thanks replying back 🙂
