### ISSUE TITLE
Determining what `maxThreads` and `minThreads` are

### ISSUE THREAD

**Issue by NickHeiner** [jasnell/piscina#147]
After constructing a `Piscina` instance, how can I determine what `maxThreads` and `minThreads` were determined to be? The docs say "The default is based on the number of available CPUs" but it would be useful to know what the actual value was.

**Comment by jasnell** [comment]
That's definitely something we can add. Interested in opening a pull request? If not, I'll try to get to it in the next week or two

**Comment by NickHeiner** [comment]
I won't have time for a PR for this, but I may be sending a PR soon with
some documentation updates. :)
