### ISSUE TITLE
Guidance - best practises regarding long running processes

### ISSUE THREAD

**Issue by RichardWright** [jasnell/piscina#154]
Hi!

If you wanted to use a thread to run a poller or persistent websocket connections, is there anything you should do to handle this? Is it even advised to do so?

Thanks for project, nice to see atomic support!

**Comment by jasnell** [comment]
Piscina is optimized for processing a queue of tasks and not really well suited for a polling mechanism. For that, I would just use worker threads directly and avoid the additional abstraction from Piscina.
