### ISSUE TITLE
How can a worker know if it's aborted?

### ISSUE THREAD

**Issue by NickHeiner** [jasnell/piscina#156]
My workflow is:
1. Enqueue many tasks.
2. When one task returns with a given value, abort all remaining tasks.

I'm using `signal` to abort my task queue. However, it seems like some tasks that are already in flight continue running. I would like to be able to kill them too. I think I may need to do something like:

```js
module.exports = async function task() {
  if (isAborted) return;
  await networkRequest1();
  if (isAborted) return;
  await networkRequest2();
  if (isAborted) return;
  await networkRequest3();
}
```

However, I'm not sure how I could get the `isAborted` signal from the `piscina.workerData` API.

Is this possible? Am I going about this the right way?

**Comment by jasnell** [comment]
From inside of a worker it's not really possible because the abort will abruptly terminate the worker thread, there's no chance given to run code after it's called. You could set up your own abort signaling mechanism as an argument input into the task tho.

**Comment by NickHeiner** [comment]
Ok – in that case, I don't need the constant `if (isAborted)` checks, and I must be misunderstanding the symptoms I'm seeing. Thanks!
