### ISSUE TITLE
Piscina is not compatable with Vercel\Pkg

### ISSUE THREAD

**Issue by rogerthoang** [jasnell/piscina#174]
I have taken one of the examples provided and attempted to use pkg to create an executable.

Upon running it, I am getting the error detailed in this repository

[piscina-example-pkg](https://github.com/rogerthoang/piscina-example-pkg)

Please advise what I can do and if this is an issue with Piscina.

**Comment by jasnell** [comment]
This would appear to be an issue with Vercel/Pkg not properly supporting Node.js worker threads by filename. You can try testing the theory by removing Piscina from the picture. Create a Node.js application that spawns a Worker thread using a filepath to identify the worker to run.

**Comment by rogerthoang** [comment]
Oh I know that works 100%, I have done that in the past. 

I only opted to use Piscina since I love the support for thread pooling and the clean API.  Any thing I can do while maintaining usage of Piscina?

**Comment by jasnell** [comment]
I haven't played around with Pkg much. If you can put together a simple reproduction I can experiment with I'll see what I can find

**Comment by rogerthoang** [comment]
> I haven't played around with Pkg much. If you can put together a simple reproduction I can experiment with I'll see what I can find

Sure thing, I have linked the repository here.

https://github.com/rogerthoang/piscina-example-pkg

**Comment by rogerthoang** [comment]
this fixed the issue:

referencing this here for future people who want to use pkg with piscina.

https://github.com/rogerthoang/piscina-example-pkg/commit/86c7504879baca5d073c40f528731d5c1a4cc382

**Comment by jasnell** [comment]
Nice! Would you maybe be interested in opening a pr to add a minimal example in the examples folder? Seems like it would be useful!
