### ISSUE TITLE
cut an array according to the number of processors

### ISSUE THREAD

**Issue by nacimgoura** [jasnell/piscina#191]
Hello, thank you for this work.
I want to use this package to parallelize the processing of several million documents, which are stored in an array variable.
I want each worker to process a part of these documents and once all the processing is finished, the program stops.
But I did not find how to tell the library to cut the array according to the number of processors.
For example with 1M elements and a 10 core processor I want each processor to process 100k elements.
I did not find how to use the library for this purpose, and if there is a better way to do it.
Have a good day!

**Comment by trasherdk** [comment]
How about `workLoad = docArray.length / os.cpus().length` :smiley:

**Comment by nacimgoura** [comment]
> 

Yes but how to use it in a pool with piscinajs?

**Comment by trasherdk** [comment]
Slice your `docArray` into `workLoad` sized arrays, and iterate

```js
pool.run(workLoadSlice, { filename: resolve(__dirname, 'worker.js') })
```
Or something like that :question:
