### ISSUE TITLE
How to use broadcastChannel

### ISSUE THREAD

**Issue by nacimgoura** [jasnell/piscina#192]
Hello,
would it be possible to add an example with [BroadcastChannel](https://nodejs.org/dist/latest-v17.x/docs/api/all.html#worker_threads_class_broadcastchannel_extends_eventtarget) because I can't transfer the instance with piscina, even through transferList.
Thanks for your work!

**Comment by jasnell** [comment]
`BroadcastChannel` itself doesn't need to be transferred. You can create a new instance of `BroadcastChannel` in the worker using the same name and they will find each other.

**Comment by metcoder95** [comment]
@nacimgoura is this still valid?

**Comment by nacimgoura** [comment]
> @nacimgoura is this still valid?

I didn't test again, but I think yes

**Comment by metcoder95** [comment]
Can you try with @jasnell suggestion? 🙂
