### ISSUE TITLE
Use generic Piscina class to typecheck `run()` parameters and return type.

### ISSUE THREAD

**Issue by arthurfiorette** [jasnell/piscina#231]
Changing the Piscina class to use a generic `T` (parameter) and `R` (possible return). This way it would be possible to get a better developer experience and intellisense while using this package.

Example: 

```ts
declare class Piscina<T = any, R = any> ... {
  ...

  run(task: T, options?: RunOptions): Promise<R>;
}
```

I'm also open to create a PR...

Thanks!

**Comment by metcoder95** [comment]
PR is welcome 🙂
