### ISSUE TITLE
Attempting to understand the `Transferable` interface

### ISSUE THREAD

**Issue by rossimo** [jasnell/piscina#276]
I've been reading the docs, and I'm assuming the `Transferable` interface is a way to efficient ship complex objects between the parent and workers. Though, I'm not sure exactly how to use it?

Looking at the example, it seems there's an object with the following interface/shape:
```
{
  a: {
    b: Uint8Array
  },
  c: Uint8Array
}
```

Once it's moved, am I understanding correctly that the parent will receive and object of that shape, and the `Uint8Array` data types will be efficiently transferred?

I guess my main point of confusion is the `transferableSymbol` and `valueSymbol`. How does `move()` know how to point `b`'s value to the transferred `b.buffer`? I see all references listed in those symbols, but I don't understand how they are mapped back to each other after the `move()`.

**Comment by metcoder95** [comment]
Hey! I’ll try to answer the question the best I can.

When transferring `object`s to threads, similar to what Web Browsers does, the [Structured Clone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) algorithm is used to properly share a clone of the object to the destination (applies to the following [types](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types)).

Now, internally Piscina does uses `transferableSymbol` and `valueSymbol` in combination with `move` to mark a value that wants to be transferred to the thread in a specific manner as when you make the use of the `Piscina.move` function, you’re basically indicating that the value you’re about to share is going to be fully moved not only shared. This means that the `ArrayBuffer` is completely unusable on the Parent thread. For instances, this operation needs to be handled in a specific way, that’s why `Piscina` makes use of such symbols to take care of standardizing the way the value is transferred to the thread.

For more info see [`worker_threads`](https://nodejs.org/api/worker_threads.html#portpostmessagevalue-transferlist).

Hope that answers your question 🙂
