### ISSUE TITLE
BigNumber loses it's typing, becomes an object

### ISSUE THREAD

**Issue by robwilkes** [jasnell/piscina#295]
Hi, it looks like when an object is cloned, it may lose its typing, I've sent (cloned) a BigNumber to piscina, and the cloned object inside piscina worker looks like a BigNumber, but isn't it's a regular object.

The value, is converted into an object like the following:
```
{
    gasUsed: {
        type: "BigNumber",
        hex: "0x01f157"
    }
}
```

it loses the BigNumber functions such as .toString() which would convert the number to a string.
instead if I call .toString() on it I get [object Object]

is there any workarounds or recommendations for this?

**Comment by robwilkes** [comment]
I just worked around it by recasting back to BigNumber again, would still like to know why they lost their typing by not worth the hassle.

**Comment by metcoder95** [comment]
The BigInt type is not currently supported by the Structured Algorithm, for instance, the Serialization/Deserialization step made when passing/receiving the BigInt does some tricks to properly pass it, but this is done at the Node.js side. Not so sure if Piscina should handle those in that specific manner but worth it to extend documentation for adding this consideration
