### ISSUE TITLE
Share JS Object in memory amongst different threads

### ISSUE THREAD

**Issue by jfoclpf** [jasnell/piscina#302]
Any hint on how to share a (big) JS Object in memory amongst different threads?

**Comment by ronag** [comment]
That's not possible in V8.

**Comment by jfoclpf** [comment]
Interesting. What about this?
https://github.com/MakarenaLabs/Shared-Memory-NodeJS-Demo-Server

**Comment by ronag** [comment]
You can share array buffers, but not js objects.

**Comment by jfoclpf** [comment]
> You can share array buffers, but not js objects.

There's no simple way to convert an array buffer to an JS object and vice-versa? `JSON.stringify`?

Can you kindly provide some example on how to share an Array Buffer amongst workers, with Piscina?

**Comment by ronag** [comment]
> There's no simple way to convert an array buffer to an JS object and vice-versa? JSON.stringify?

That's not sharing... that's just copying... piscina does this out of the box. You don't have to do anything.

**Comment by jfoclpf** [comment]
Good point.

And how can I share in memory an Array Buffer with Piscina?

**Comment by tripodsgames** [comment]
Maybe you can use this:
https://github.com/Bnaya/objectbuffer

**Comment by metcoder95** [comment]
@jfoclpf closing the issue, please feel free to reopen it if this is still a problem
