### ISSUE TITLE
How to make piscina bidirectional? (from parent to worker)

### ISSUE THREAD

**Issue by jon9090** [jasnell/piscina#303]
In the message_port example, there is a way to send a message to the worker. 

But is it possible to send a message from the parent to the worker?

I tried this, but it did not work:

```
  channel.port2.on('message', (message) => {
    console.log('im msg')
    channel.port2.emit('bla');
    channel.port2.postMessage('bla');
    channel.port1.emit('bla');
    channel.port2.postMessage('bla');

...
export default async ({ port }: { port: MessagePort }) => {
  console.log('run');
   port.onmessage = () => {
    console.log('in onmessage');  
 }
  port.addEventListener('message', () => {
    console.log('in msg');
  });
```

https://github.com/piscinajs/piscina/blob/current/examples/message_port/worker.js#L4

Is it possible to do?

**Comment by metcoder95** [comment]
Yes is possible, see the following reference from Node.js when using `MessageChannel` for establishing bidirectional communication: https://nodejs.org/api/worker_threads.html#class-messagechannel
