### ISSUE TITLE
child thread may never end

### ISSUE THREAD

**Issue by BTYHunter** [jasnell/piscina#321]
hi guys, I have a program to extract a zip file. In order to make use of muti CPU I choose Piscina serve as my thread pool. My program idea is divide a ZIP file into many parts, suppose there is ZIP file A contains 30000 files, my main thread is to get A file，use Piscina make child threads, each child thread unzip 4000 files.
here is my code.
main thread is:
```
// get file TEST.zip from aws s3
// suppose TEST.zip has 30000 files
// devide 30000 into 8 parts, each parts has 4000 files (last part 2000)

const piscina = new Piscina({
  filename: resolve(__dirname, 'worker.js'),
  minThreads: 1,
  maxThreads: 4
})

const countArr = [1,2,3,4,5,6,7,8]
await Promise.all(countArr.map(async (item) => {
  const result = await piscina.run(item)
  outPutLogs(`receive message from child thread, message is: ${result}`)
}))
```

child thread worker.js is:

```
// get TEST.zip from aws s3
// child thread , unzip 1-4000 files;
// child thread , upzip 4001-8000 files;
// ..
// child thread , unzip 28001-30000 files;

module.exports = async (item) => {
  let files = getFileFromAWSS3(item)
  let result = unzipFiles(files)
  outPutLogs(`extract done, result is: ${result}`)
  return (`extract done, child thread ID is: ${item}`)
}
```

what confused me is that, this program prohaps never end, it seems like some child thread will never start (or get TEST.ZIP from aws s3). sometimes child thread 2\4 never start, sometimes child thread 7\8(the numbers is random) never start, sometime (only one) all threads done.
Is there something wrong with my program? it looks like some child thread may never get resource to execute.

thx and appreciate

**Comment by metcoder95** [comment]
Hey! The bare minimum number of threads you want to run, and the max threads that can be spawned are, by default if not customized, the CPU Cores of the host to come with the right amount of threads to be spawned.

If you want to customize it and ensure always to have at least 8 threads (maybe because this is the number of cores in your machine's CPU) you'll need to customize the `maxThreads` and `minThreads` options when instantiating Piscina, see [this](https://github.com/piscinajs/piscina#constructor-new-piscinaoptions) for more info.


Here it seems you're facing such issue, give it a shot customizing those properties 🙂

**Comment by BTYHunter** [comment]
Thanks very much.
I try it many times and still can't figure it. Say `maxThreads ` set to 4(cores in my machine's CPU) and `minThreads ` sets to 1.
I found that if the TEST.zip is a smaller file, say 2MB and has 200 files (each thread handles 20 files), the program works very well and each thread behavior well. When TEST.zip is a lagger file, say 80MB and has 30000 files (each thread handles 4000 files),  sometime works well, very often some child thread hang-up waiting for get AWS S3 objects.
I execute program with 2GB still can't figure it.
`time node --max-old-space-size=2048 ./src/main.js`
any suggestions 🙂

**Comment by BTYHunter** [comment]
Thx very much. I found that is network I/O limit result the AWS S3 not return full data that I request. 🙂
