### ISSUE TITLE
throw error with histogram

### ISSUE THREAD

**Issue by wszgrcy** [jasnell/piscina#327]
![image](https://user-images.githubusercontent.com/9607121/216221772-970b6f59-f85b-4a5a-8f5a-6f41d3fc9b18.png)
I use piscina with electron .In my develop computer, It works well.but when I build and run in virtual box (win 10 22h2 new system),code run 2~3s and throw err   I add `try ... catch` in my code but Error still reported
If I add `console` in my worker.js, It also works well..... `Piscina instance` as follow
```typescript
  get pinyinWorker() {
    if (!this.#pinyinWorker) {
      this.#pinyinWorker = new Piscina({
        filename: path.join(__dirname, 'worker', 'worker.js'),
        minThreads: 2,
        maxThreads: 4,
        idleTimeout: 120_000,
      });
    }
    return this.#pinyinWorker;
  }
```

**Comment by metcoder95** [comment]
Hi, @wszgrcy Is this stills valid?
