### ISSUE TITLE
a large value of maxThread drops the script without any information

### ISSUE THREAD

**Issue by gachi-lord** [jasnell/piscina#341]
I'm trying to set maxThread to 10 or 20, like this
   ```javascript
сonst piscina = new Piscina({
        filename: path.resolve('./', 'processor.js'),
        maxThreads: 20
    })
``` 
Later in the code, I call piscina.run() in the for...of loop
```javascript
 for (let chunk of chunks) { //there are few objects here, 10-14
      piscina.run({ chunk }).then(console.log)
 }
``` 
The first 30 times everything works fine, but then the script just stops. Moreover, I am sure that this is impossible, because there is an infinite loop without break and return. I also noticed a correlation such that the less I set maxThread, the longer the script runs. maxThread:1 runs non-stop. I also disconnected Piscina from my code, and everything worked fine, so I'm sure that the problem is in this library. I would be happy to provide more information, but the script stops completely without any additional information. I tried to put interceptors on the process object, but they gave absolutely nothing. I would like to know more about this behavior of the library, and what it is related to. I guess the problem is in memory.

**Comment by metcoder95** [comment]
The `maxThreads` is getting out of bounds, you should try to make them cope with the CPU cores available in your machine. It might be possible that the kernel itself is killing the process due to resource starvation, you'll need to track that down.
But as a rule of thumb, try not to have more threads than CPU cores.
