### ISSUE TITLE
use `Atomic.waitAsync` instead of `Atomics.wait`

### ISSUE THREAD

**Issue by ronag** [jasnell/piscina#346]
In order to not fully block the thread and allow background stuff to continue running.

**Comment by metcoder95** [comment]
It will be definitely a breaking change but can be really helpful as it is a constant gotcha that is not easy to perceive at first glance.

Do you see it more beneficial to replace it at all or make it optional could be an option as well?

**Comment by ronag** [comment]
Maybe add the option to pass "async" to the useAtomics option?

**Comment by metcoder95** [comment]
SGTM 👍 
+1 for doing it
