### ISSUE TITLE
More customisable scheduling

### ISSUE THREAD

**Issue by ronag** [jasnell/piscina#347]
Currently, piscina only supports depth-first scheduling. It would be nice to be able to add more scheduling strategies based on different types of heuristics.

A bit like https://github.com/poolifier/poolifier but not necessarily as advanced.

**Comment by metcoder95** [comment]
We can start with something small like Round Robin, and its weighted version. And allow, through options, how to assign weights and other moving pieces.

+1 on going for it 👍
