### ISSUE TITLE
How to check if queue has room before enqueuing

### ISSUE THREAD

**Issue by ronag** [jasnell/piscina#348]
Currently the only way to know if further tasks can be scheduled is through `runTask` and catching an error, which is not optimal.

Is something like this possible to add?

```
if (!worker.isFull) {
  worker.runTask(task)
}
```

**Comment by metcoder95** [comment]
It would be actually really helpful, it should be straightforward.

The following set of lines does verify the queue depth size based on the configuration values and decides whether or not to enqueue/post tasks to any available worker.

https://github.com/piscinajs/piscina/blob/bcae345594fa5a6c306bff207fc95c14b021293a/src/index.ts#L803-L816

It is a matter of abstracting the maths from these two lines:
https://github.com/piscinajs/piscina/blob/bcae345594fa5a6c306bff207fc95c14b021293a/src/index.ts#L804-L805

It can also be a refactoring opportunity 🙂

**Comment by ronag** [comment]
Duplicate of https://github.com/piscinajs/piscina/issues/126
