### ISSUE TITLE
Block the others thread when set minThreads = 1

### ISSUE THREAD

**Issue by kienlv58** [jasnell/piscina#392]
When I run many task parallel, It running not correctly. It will do it sequentially.
My task:

```
import LoggerService from '../../src/lib/loggerService';

const loggerService = new LoggerService();
export default (): string => {
  loggerService.info('Start perform task 1');
  const startTime = Date.now();
  while (Date.now() - startTime < 5000) {
    // Perform some computation
  }

  loggerService.info('Done perform task 1');
  return 'default task success';
};

export async function sum(data: { arg1: number; arg2: number }): Promise<number> {
  loggerService.info('Start perform task 2');

  await new Promise((resolve) => {
    setTimeout(() => {
      resolve(1);
    }, 7000);
  });
  loggerService.info('Done perform task 2');
  return data.arg1 + data.arg2;
}
```

And worker run:

```

const [first, last] = await Promise.all([
      workerPool.run(
        {},
        {
          filename: require.resolve('./tasks'),
        }
      ),
      workerPool.run(
        { arg1: 2, arg2: 3 },
        {
          filename: require.resolve('./tasks'),
          name: 'sum',
        }
      ),
    ]);
```

It alway wait task 1 finish and then do task 2.
Worker instance:

```
workerPool = new Piscina({
    idleTimeout: 5000,
    minThreads: 1,
    execArgv: __filename.split('.').pop() === 'ts' ? ['-r', 'ts-node/register'] : undefined,
  });

```

I log to see the workerPool.threads.length still = 2. What happens?

**Comment by metcoder95** [comment]
Hey! Can you elaborate on your problem? It does not seem clear what issue you are facing.

If running in parallel, `Promise.all` won't help you to see that as it will wait until all Promises are fulfilled or at the first rejection.
The time to spin up some threads also matters, as it requires `piscina` to create a freshly new thread to consume tasks.

**Comment by kienlv58** [comment]
@metcoder95 
I found the problem.
My code run in the test.spec.ts use jest.
And seem like only 1 thread to run all task.
The code run when not using jest is correct. The log show will be:
Start perform task 1
Start perform task 2
Done perform task 1
Done perform task 2

But the log when run use jest environment:
Start perform task 1
Done perform task 1
Start perform task 2
Done perform task 2
That means it runs sequentially in jest test

**Comment by metcoder95** [comment]
I need to admit that I might not be impressed that this only happens in `jest` 😅 

Most likely Jest is doing something extra that limits the creation of threads by Piscina (+ globals). We might need to dig deeper into it, but I'd suggest moving away from `jest` for this kind of testing.
Any contribution and suggestion is welcomed to solve the problem 🙂
