### ISSUE TITLE
Feature: `'drain'` event

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#41]
We should add a `piscina.on('drain', () => {})` event that is fired once all currently pending tasks have been either completed or dispatched to workers. The use case is to provide a signal for when it may be ok to start submitting tasks to the queue again. Specifically, if I am using a stream to push tasks into the queue, but I approach the queue limit, I want to pause the inbound stream to apply backpressure... then, once the queue has reached zero, I want a signal to indicate that I was unpause the feeding stream and resume submitting tasks.

We should consider carefully how this works because the timing of the event can be a performance bottleneck. For instance, if we wait until the all tasks are completed, then our queue will go idle while we wait for the next tasks to be submitted, which could cause our workers to be terminated unnecessarily. However, if we fire the drain event too early we could add churn.

One idea would be to set a load threshold as a percentage of queue limit as a configuration option for the drain event. That is, when queue limit is not unlimited, setting a load threshold of 0.25 would mean that when the queue size is 25% of the queue limit, the `'drain'` event is emitted allowing us to start filling the queue back up.

Wanted to make sure we discussed the strategy on this before working on the implementation.

**Comment by addaleax** [comment]
@jasnell I think there would be two approaches here, if the goal is to know whether new tasks would be accepted.

- Just unconditionally emit an event when a task is done. That’s easy and gives a lot of flexibility, in particular considering that `pool.queueSize` exists.
- We could emit an event once `pool.queueSize` drops to zero, or alternatively if there is one open slot that could be filled (i.e. `pool.queueSize` is zero + an additional task has drained).

A load threshold for the queue would still mean that tasks are being queued up and not immediately being processed – not sure whether that’s really the most desirable thing.

**Comment by jasnell** [comment]
Either way, emitting an event when a task is done may be a good idea regardless.

For the threshold, setting a value of 0% (which could be the default) would mean emitting the `'drain'` when `pool.queueSize` drops to zero which would accomplish that particular case.

Queuing up tasks that aren't immediately processed while other tasks are still pending might actually be desirable if the latency of waiting for new items is more expensive than the actual processing cost (that is, if we know we're processing items fast enough that queuing those up isn't going to be a problem). By the time our stream is able to resume, it's possible and likely that the queue size will drop even further.

**Comment by jasnell** [comment]
This is done!
