### ISSUE TITLE
How can I pass service between service and workers?

### ISSUE THREAD

**Issue by walldba** [jasnell/piscina#412]
I'm trying to use Piscina in a Nest application.
I want my WorkerPool class to create an instance of Piscina and pass the services to worker use when called. I don't know if it's the best approach.

**Problem to solve:**
I want to do two HTTP requests in different threads because each httpRequest mustn't have block the event loop in case of a long duration or error. Thinking in this scenario, I believe using worker_threads is the best approach.

I'm right?

Example WorkerPool (service): 

```javascript
@Injectable()
export class WorkerPool implements OnApplicationBootstrap {
  private pool: Piscina;
  constructor(private readonly someService: SomeService) {
    this.pool = new Piscina({});
  }

  onApplicationBootstrap() {
    this.start();
  }

  public start() {
    this.pool.run(this.someService, {
      filename: resolve(__dirname, 'worker'),
    });
  }
}

export class SomeService {
  //The constructor receives some services by DI. (HttpService for example)
  constructor() {}

  public execute() {
    console.log('executing...');
  }
}
```

Example of worker:
```javascript

import { SomeService } from './worker.pool';

export default async function teste(someService: SomeService) {
  await someService.execute();
}
```

**Comment by metcoder95** [comment]
Hey!

Given how the data is transferred between threads, what you are looking to achieve is not possible. To transfer objects, `worker_threads` uses [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) algorithm/API to pass the given data to the thread and back.

This means that methods or functions are not transferrable.

Your approach is right, but the service should be instantiated directly within the worker thread, not passed from the parent.

**Comment by RichardWright** [comment]
@metcoder95 I can't find a usage of structuredClone in this codebase? has this moved on?

**Comment by metcoder95** [comment]
The `structuredClone` implementation its pat of `worker_threads` implementation, not a Piscina thing per se
