### ISSUE TITLE
Threads are re-created when calling `destroy`

### ISSUE THREAD

**Issue by alan-agius4** [jasnell/piscina#427]
## Problem
When Piscina is destroyed the worker threads are re-created 
```js
import { Piscina } from "piscina";

const piscina = new Piscina({
  maxThreads: 8,
});

console.log(`Number of threads: ${piscina.threads.length}`);

piscina.destroy().then(() => {
  console.log("Destroyed.");
  console.log(`Number of threads: ${piscina.threads.length}`);
});

```
Outputs
```
Number of threads: 8
Destroyed.
Number of threads: 8
```

Version: 4.1.0

## Other info
The issue appears to be caused because when a worker is terminated it is threaded as an error and this._ensureMinimumWorkers(); ends up being invoked.
https://github.com/piscinajs/piscina/blob/b96fa78363ec1f8c54f9d63c1909156b8c9749c5/src/index.ts#L695

**Comment by metcoder95** [comment]
Hey!
Sadly I couldn't reproduce your example:
Using your reproduction provided, I got the expected outcome:

```js
import {Piscina} from 'piscina';

const piscina = new Piscina({
  maxThreads: 8,
});

console.log(`Number of threads: ${piscina.threads.length}`);

piscina.destroy().then(() => {
  console.log("Destroyed.");
  console.log(`Number of threads: ${piscina.threads.length}`);
});

setTimeout(() => {
  console.log(`Number of threads: ${piscina.threads.length}`);
}, 1000)
```

```shell
Number of threads: 5
Destroyed.
Number of threads: 0
Number of threads: 0
```

I don't think that might be the problem, as the thread gets terminated instead of exited with an error, but maybe if you can provide another 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) close to your actual implementation, we can validate that 🙂

**Comment by alan-agius4** [comment]
@metcoder95 I can replicate the reported problem also on www.npm.runkit.com


<img width="1099" alt="Screenshot 2023-10-20 at 13 41 59" src="https://github.com/piscinajs/piscina/assets/17563226/6eea59a4-00d4-43a3-999c-19099221624e">

The problem is that on termination the `_onError` is invoked https://github.com/piscinajs/piscina/blob/b96fa78363ec1f8c54f9d63c1909156b8c9749c5/src/index.ts#L683-L700 `workerInfo.isReady() && !this.workerFailsDuringBootstrap` is truthy which causes the workers to be re-created as `_ensureMinimumWorkers` is called.

It appears that https://github.com/piscinajs/piscina/commit/8e6d16e1dc23f8bb39772ed954f6689852ad435f introduced the problem.
