### ISSUE TITLE
Increase memory consumption

### ISSUE THREAD

**Issue by sollidy** [jasnell/piscina#442]
Hi! I use piscina worker with three.js inside nest.js. After each operation i destoy worker (await piscina.destroy()). But as if the memory is not completely cleared. Is it right way to clear workers or not?
### On screenshot statistic from pm2. Every memory jump is the starting of a worker
![memory](https://github.com/piscinajs/piscina/assets/70297692/7c6ca3b1-7630-4728-9f2d-2490db5d0c95)

**Comment by metcoder95** [comment]
Hey! Thanks for the report
Can you provide a 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to help you in a better way?

From what I'm seeing, it is kind of expected the jumps as are the cost of spawning the threads. But I'm also wondering how and when are you clearing the worker pool

**Comment by sollidy** [comment]
@metcoder95
like that
```ts
const piscina = new Piscina({...})
class Converter = {
  constructor(...piscina: Piscina){}
  const result =  await this.piscina.run()
  await this.piscina.destroy()
}
```

**Comment by metcoder95** [comment]
I tried to reproduce it but the sampling its pretty consistent, the resources from the threads are freed almost immediately and the rest through the gc. I might guess it might be something else within your workload causing a memory leak.

Do you have a more close-to-real example?

**Comment by pavelkornev** [comment]
I observe the same issue with memory using latest v4.1, i had to switch back to v3.2.0 where there is no such an issue.

With v3.2.0 there is another issue, TS types are not part of the `export` property of `package.json` which is causing some issues, but `ts-ignore` helps :\

**Comment by metcoder95** [comment]
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), maybe I'm missing something on the reproduction.

>With v3.2.0 there is another issue, TS types are not part of the export property of package.json which is causing some issues, but ts-ignore helps 

Hmm, can you fill another issue to tackle this down

**Comment by pavelkornev** [comment]
> Can you provide an [Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), maybe I'm missing something on the reproduction.

I would love to do this, but in my case it's impossible as the project uses many internal dependencies. I can give some constrains:

- 10K heavy tasks scheduled
- Every 100 tasks we recreate the worker (in v3.2.0 memory is released, with v4 it's not)
- Yes, there might be some memory leaks in the heavy tasks, but those are coming from 3rd party libraries and this is also a reason we use piscina to isolate and control memory, beside the parallel execution.
- Memory consumption on MacBook Pro with 32Gb RAM jumps to 45Gb (incl. Swap), with v3.2.0 it's all around 1.5Gb during the whole execution of all tasks.
- Node v20.9.0 (LTS as of Nov 2023).

> > With v3.2.0 there is another issue, TS types are not part of the export property of package.json which is causing some issues, but ts-ignore helps
> 
> Hmm, can you fill another issue to tackle this down

Done - https://github.com/piscinajs/piscina/issues/446

**Comment by metcoder95** [comment]
Without reproduction is kind of hard to guess what’s happening. Locally with really simple code, I’m seeing the memory being freed after every `destroy` call

**Comment by pavelkornev** [comment]
still relevant..

**Comment by JaoodxD** [comment]
> still relevant..

How long does it take to notice the leak?  
Will try to reproduce in the spare time so if you have anything to add to [this](https://github.com/piscinajs/piscina/issues/442#issuecomment-1817962643), you're welcome
