### ISSUE TITLE
TypeScript + ESM modules + piscina v3.2.0

### ISSUE THREAD

**Issue by pavelkornev** [jasnell/piscina#446]
When using piscina v3.2.0 and TS+ESM, there is such an issue:

```
Could not find a declaration file for module 'piscina'. '/Users/pavelkornev/workspace/my_project/node_modules/piscina/dist/esm-wrapper.mjs' implicitly has an 'any' type.
  There are types at '/Users/pavelkornev/workspace/my_project/node_modules/piscina/dist/src/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'piscina' library may need to update its package.json or typings.
```

Basically, the reason is the incorrect exports.

This problem is solved in v4. If it's possible to downport and make a release for v3, it would be great as we cannot migrate to v4 due to the memory issue #442

**Comment by metcoder95** [comment]
Sadly we cannot backport as we dropped the support completely. If the memory issue is the key case here, let's focus our efforts on that the 👍
