### ISSUE TITLE
How to distribute message data to each worker?

### ISSUE THREAD

**Issue by imjuni** [jasnell/piscina#461]
I want to develop a cli that uses the TypeScript Compiler API. A project that loads a project and then analyzes the interface or type information to generate a JSONSchema or generate other code.

I want to use workers when generating other code to improve performance, is there a good way to distribute the work to multiple workers, like if I pass [1,2,3,4,5,6,7,8,9] to the "postMessage" function, the first worker will take [1,2,3], the second worker will take [4,5,6], and the third worker will take [7,8,9].

```ts
const cpus = os.cpus().length;
  const mc01 = new MessageChannel();
  const pool = new Piscina({ filename: filePath, minThreads: cpus });

  setTimeout(() => {
    mc01.port2.postMessage({ task: 1, params: { name: 'hello 1', task: [1,2,3,4,5,6,7,8,9] } });
  }, 3000);

  setTimeout(() => {
    mc01.port2.postMessage({ task: 3, params: { name: 'hello 2' } });
  }, 6000);

  await Promise.all([
    pool.run({ port: mc01.port1, cpus }, { transferList: [mc01.port1], name: 'working' }),
  ]);
  ```

**Comment by metcoder95** [comment]
Hey!
The default balancing algorithm from Piscina is a plain FIFO, meaning that maybe initially you'll distribute the load evenly and in order, but most likely the outcome will be out of order and at some point the task distribution will remain the same.

You can do several things to achieve this, from adding an incremental ID to each task and reconciling after all the tasks are processed.

Another option is to use a [Custom Task Queue](https://github.com/piscinajs/piscina#custom-task-queues) that enables you to distribute the load accordingly and in the order you are looking for.
