### ISSUE TITLE
Thoughts on m:n worker mapping?

### ISSUE THREAD

**Issue by jdmarshall** [jasnell/piscina#474]
We have an app that's a bit of a mess. Each request can get sucked into one of a handful of complex tasks which require CPU and local copies of shared resources. We end up running 1 process per core to improve fairness, but it seems like a titanic waste of resources, having so many copies of our code and static files loaded just to avoid CPU stalls, and every process having to arrive at the same lazily cached data set independent of each other. And even with all this we still have to add throttling code in spots to keep from creating Thundering Herd situations with other services.

I keep coming back to wanting something a bit more Erlang like, where we segregate the heaviest lifting into several distinct processes that are called by the routing code, or by each other, so that we have around 6 copies of each per server. Same number of processes, fewer caches, better peak traffic control. 

I'm loathe to use sidecars for this because of the deployment nightmare this entails around change management. I think I'd be much better off with shared workers. And while I believe I know how to cheese such a thing within Piscina, by stealing and redistributing communications channels between processes, I would lose most of the API surface area in the process.  

I'm wondering how thin a wrapper one could make or how much code it would take to get piscina to handle this better. It feels like a solution might be for extra behavior if piscina is itself called from a worker started by piscina, if it could negotiate with the parent process to avoid duplicate worker pools.

**Comment by metcoder95** [comment]
Hey!

To understand correctly what you are suggesting, the idea is to have a Piscina instance that spawns threads that also spawn more Piscina instances with more threads that handle the load accordingly.

Theoretically, this should not be an issue; worst-case scenario you'll have threads stealing CPU time from the other, and most likely if you have it behind a synchronous service (e.g. HTTP server) it can also hit you, but I wouldn't take it for granted unless you already tested by yourself.

To do such coordination, and even maybe try to implement work-stealing, you can take a look at the [following example](https://github.com/piscinajs/piscina/tree/current/examples/message_port) for message communication between main and child thread.

I imagine the chore of the work will leave within the coordination of those Piscina instances, so that might be enough (?).

>I keep coming back to wanting something a bit more Erlang like, where we segregate the heaviest lifting into several distinct processes that are called by the routing code, or by each other, so that we have around 6 copies of each per server. Same number of processes, fewer caches, better peak traffic control.

Yeah, that would be amazing

**Comment by jdmarshall** [comment]
Let's say I start with piscina at the top level instead of the cluster module, now all of my Koa/Express/Nest instances are running as workers. And let's say I want to occasionally compile a stylesheet or rebuild a template in those, but I want to bottleneck that to say 5 tasks so that one user can't monopolize the server.  

And then someone else likes this idea so much they do the same with another subsystem or 2.  

I don't need to just send a task to an arbitrary worker, I need some of the fairness/load balancing that piscina and some other libraries try to provide.

The closest I could get now is to run a few services in the same docker container. Otherwise I'm converting them to full services and dealing with deployment issues and inter-version compatibility surface area. Or just putting up with the unfair system we already have because this is too much work to sell people on (people possibly being 'me')

**Comment by metcoder95** [comment]
Hmm, that's interesting.

So far, currently, piscina does not offer _stickiness_ unless you set them manually while providing your task scheduling algorithm (which can be done as shown [here](https://github.com/piscinajs/piscina#custom-task-queues)).

The `default` load balancing from Piscina is a simple `FIFO`, but we have seen requests to offer more algorithms out-of-the-box.

Here I imagine a weighted or least-used distribution; currently, Piscina does not offer that but can be manually implemented using a custom queue, although it misses the Worker info to understand its load.

Based on that, maybe we can start by allowing Piscina to offer that worker info to the Task Queue, and that might help you with the implementation.

But overall, it should not be a problem have a thread cluster with Piscina instances from threads.

**Comment by jdmarshall** [comment]
the cluster module is fairly averse to the idea of swapping the LB algorithm.  Having that in piscina would be another 'pro' for switching for at least some of us.

Even ignoring the bigger picture here, there would be benefit from supporting least-conn and probably random-2 for piscina.  Might speed up a couple of batch processing cases that I have.

**Comment by metcoder95** [comment]
Yeah, I'd see if I have any bandwidth in the upcoming weeks to kick-off something, PRs are welcome if you are interested in 🙂

**Comment by jdmarshall** [comment]
I poked at the code, and it bears a very passing resemblance to a problem I'm solving at work with a memory leak in a caching system that is not handling publish-triggered evictions properly. I need to keep a class of data together so I can drop it as a single action instead of scanning for candidates.

Essentially you are treating all of the workers as part of a shared state and then scanning them for availability. 

I think it might do as a first step if you were to segregate the workers into a busy (saturated) and available list. Because there's a lot of code in the distribution system that concerns itself specifically with that case.

Then we can talk about how one might go about using a different mechanism to pick among a list of slightly idle workers. For instance with a limit of 3, how would you maintain a fair distribution of work (not tasks) across the workers to improve response time. Particularly with tasks with variable work. 

Another solution is to distribute all messages at receipt, but that would necessitate implementing work stealing. However since any mature distributed computing implementation ends up with work stealing, that may not be so bad.

That said, all of this may be at odds with my original request, depending on implementation.

**Comment by metcoder95** [comment]
Yeah, the _default_ balancing is basic, a normal FIFO until you find an available worker.
We also have support for custom queues, but it lacks the overall information about the set of workers to decide which of them distributes the load.

My idea is the following:
1. We expose more internal data at the Custom Queues
2. We create a bare basic load least-busy strategy that can be used out of the box.

**Comment by jdmarshall** [comment]
I came up with a simpler way to maybe tackle this problem, except it won't solve the problem I originally had because it's incompatible with this section:

https://github.com/piscinajs/piscina?tab=readme-ov-file#out-of-scope-asynchronous-code

Pushing stuff out of process because it randomly runs expensive background tasks should be a use case for worker pooling. How wedded are you to this design? What would happen if someone wanted to make this step optional?

**Comment by metcoder95** [comment]
See #687

**Comment by jdmarshall** [comment]
That’s a big boy but I’ll keep an eye on it.

**Comment by jdmarshall** [comment]
@metcoder95 NodeJS has BroadcastChannel that could almost allow coordination between workers, but its api is basically a toy and it doesn't give you any way to introduce two threads. 

They are now working on this... thing:

https://nodejs.org/api/worker_threads.html#workerpostmessagetothreadthreadid-value-transferlist-timeout

Which could in theory be used to introduce workers to each other. But none of this should be this hard because BroadcastChannel has a field called ~~origin~~ source and one called ports but it's empty in Node.

**Comment by metcoder95** [comment]
That's a good feature, still in WIP as you suggests; one other option could be the possibility to make the Parent an orchestrator. Worker replies back with its ID and Parent can create a Message Channel with another Thread and keep it on a Map.

Is a bit more complex and possibly easy to be a problem compared to the message to thread, but might be possible

**Comment by jdmarshall** [comment]
I’m currently trying to add worker support to a Prometheus aggregator and that’s a situation where “supervisors” really shouldn’t be the solution. Everyone needs to report to one aggregator no matter how they were born. Cross-cutting concern. There are situations where that’s fine, I suppose, but that’s more 1:k relationships.

Working on prom-client has also beat me over the head with how much Node is limited in performance by the costs of string conversions. Not just for IPC but also for lookup tables. Make JSON.parse() and stringify() even just 15% faster, or string interpolation, and you’d change the shape of the Node landscape. 

It’d be great if any of the transferrables were more amenable to interactive IPC instead of one and done style. I suppose there’s a reason all of their examples are displaying the latter. Which I suppose is why piscina exists.

**Comment by metcoder95** [comment]
>I’m currently trying to add worker support to a Prometheus aggregator and that’s a situation where “supervisors” really shouldn’t be the solution. 

This sounds like an interesting project, do you have a repo already in place?

>Working on prom-client has also beat me over the head with how much Node is limited in performance by the costs of string conversions. Not just for IPC but also for lookup tables. Make JSON.parse() and stringify() even just 15% faster, or string interpolation, and you’d change the shape of the Node landscape.
>It’d be great if any of the transferrables were more amenable to interactive IPC instead of one and done style. I suppose there’s a reason all of their examples are displaying the latter. Which I suppose is why piscina exists.

Agree with what you mean.

Most of the string conversions are a bit expensive given either the spec or by the dynamic nature of the language, which makes it harder to do proper memory management while implementing these kind of string allocation features; IPC communication when using threads is one of them.

This is something I've been experimenting trying to avoid it by using direct buffer allocation and handling. Currently my idea was to just set it for specific data structures that allows streaming of data rather than actual all kind of data that will require serialization/deserialization.

The semantics are good enough to implement not so complex architectures, but when needs become detailed and performance is a must, the limitations of these APIs arises (e.g. the fact that you cannot transfer an object reference/pointer but rather serialize/deserialize)

**Comment by jdmarshall** [comment]
> This sounds like an interesting project, do you have a repo already in place?

I do but it’s dependent on a rather large PR that hasn’t landed yet. 

Everything before 8e154daa597f1603c212c70b11a6978f0691175d is from that other PR, which I’m hoping will land shortly, because it’s got a bunch of time and space improvements. 

https://github.com/cobblers-children/prom-client/tree/workers

It needs more test coverage. But the same is true of the source material.

> This is something I've been experimenting trying to avoid it by using direct buffer allocation and handling. Currently my idea was to just set it for specific data structures that allows streaming of data rather than actual all kind of data that will require serialization/deserialization.

I stumbled upon DataView while researching this feature request. It seems slightly less awful. All of the faster JSON libraries rely on schema, which is still a draft. In the Prometheus case there could definitely be a schema. But I haven’t played with these enough to know how difficult they are to debug. And it’s probably not up to me to introduce a dependency for a feature not everyone uses.

**Comment by metcoder95** [comment]
>I stumbled upon DataView while researching this feature request. It seems slightly less awful. All of the faster JSON libraries rely on schema, which is still a draft. In the Prometheus case there could definitely be a schema. But I haven’t played with these enough to know how difficult they are to debug. And it’s probably not up to me to introduce a dependency for a feature not everyone uses.

Overall direct buffer management will lower the barrier for more performance at a cost of no direct serialization/deserialization; but as you said, most of the libraries relies on an schema to allow comprehensive approach as well take advantage of V8 optimizations.

**Comment by jdmarshall** [comment]
https://v8.dev/blog/json-stringify

This could be huge.

**Comment by metcoder95** [comment]
Saw the title yesterday, but haven't read it yet; let me take a look
