### ISSUE TITLE
The value of "val" is out of range

### ISSUE THREAD

**Issue by javigualde** [jasnell/piscina#491]
Hello,

We are having a random issue we can't debug in development, but it's throwing exceptions in production.

The error says:

[ERR_OUT_OF_RANGE]: The value of "val" is out of range. It must be a safe integer greater than 0. Received 0

We attach a screenshoot of all the exception stack trace.

<img width="965" alt="Captura de pantalla 2024-01-22 a las 19 43 26" src="https://github.com/piscinajs/piscina/assets/16036481/9f0f9c44-748e-47ec-9a85-bfd9adfcc76e">

Someone having the same issue?

Regards.

**Comment by metcoder95** [comment]
👋 

Hmm, interesting; can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by akkerman** [comment]
I got this same error when using an example from the book Multithreaded Javascript. 

Versions used:

Node:  16, 18, 19 (20 gives a different error)  
Piscina: 4.3.0  

Here is the code example:

```javascript
const Piscina = require('piscina')
const assert = require('node:assert')
const { once } = require('node:events')

if (!Piscina.isWorkerThread) {
  const piscina = new Piscina({
    filename: __filename,
    maxQueue: 'auto'
  });

  (async () => {
    for (let i = 0; i< 10_000_000; i++) {
      if (piscina.queueSize == piscina.options.maxQueue) {
        await once(piscina, 'drain')
      }
      piscina.run(i).then(squareRootOfI => {
        assert.ok(typeof squareRootOfI === 'number')
      })
    }
  })();
}

module.exports = num => Math.sqrt(num)
```

**Comment by metcoder95** [comment]
I was able to reproduce it after some time, it seems that for faster workloads, the difference in nano is 0 causing the histogram go out of bounds.

I'll prepare a fix for it soon
