### ISSUE TITLE
resourceLimits Working

### ISSUE THREAD

**Issue by SiDDhartharG** [jasnell/piscina#492]
I am operating a server that runs 20 threads, primarily tasked with executing JavaScript code provided by users. 

Occasionally, this user-provided code either contains memory leaks or is highly memory-intensive. In situations where the memory consumption of a task or thread exceeds a certain threshold (such as 200MB), I need a way to terminate that specific task or thread.

Can Piscina offer any functionality to assist with this requirement? 
I would appreciate some guidance on this matter.

**Comment by metcoder95** [comment]
👋 
You can use `resourceLimits` options when instantiating `Piscina`, those will be automatically forwarded to any `Worker_Thread` instance at the moment of spinning up a new thread:

[Reference](https://nodejs.org/api/worker_threads.html#new-workerfilename-options)
