### ISSUE TITLE
Make Max Threads default to `os.availableParallelism()` https://nodejs.org/api/os.html#osavailableparallelism

### ISSUE THREAD

**Issue by metcoder95** [jasnell/piscina#497]
I think we could default it to `os.availableParallelism()` https://nodejs.org/api/os.html#osavailableparallelism

_Originally posted by @RafaelGSS in https://github.com/piscinajs/piscina/pull/487#discussion_r1467637405_

**Comment by BenzeneAlcohol** [comment]
Hi, can I take this issue up?

**Comment by metcoder95** [comment]
Please! 👍
