### ISSUE TITLE
RangeError in Piscina -> RecordableHistogram 

### ISSUE THREAD

**Issue by geertbrit** [jasnell/piscina#532]
I'm getting the following error sporadically on Piscina 4.3.0

```
RangeError [ERR_OUT_OF_RANGE]: The value of "val" is out of range. It must be >= 1 && <= 9007199254740991. Received 0
    at RecordableHistogram.record (node:internal/histogram:283:5)
    at ThreadPool.runTask (/root/xxx/server/node_modules/piscina/dist/src/index.js:699:23)
    at Piscina.run (/root/xxx/server/node_modules/piscina/dist/src/index.js:912:65)
```

It's weird since I've been running similar code for ages and never seen this. Now overnight I'm seeing a couple dozen occurences. 

(For now hopefully mitigated using the very timely  Piscina 4.4.0 release with `recordTiming: false`)

**Comment by metcoder95** [comment]
👋 
Do you have an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) that can be used?
