### ISSUE TITLE
When I try to send a message to the worker thread, an error occurs

### ISSUE THREAD

**Issue by tocha688** [jasnell/piscina#549]
It is obvious that the message encapsulated internally is different from the data I sent, and I don't think this should happen. I need to communicate between the main thread and the worker thread. You should check if the content sent or received is an internal method, but you did not do so, or if you have customized a postMessage method
```
worker.postMessage({data:{}})
```

```
TypeError [Error]: String.prototype.startsWith called on null or undefined
    at startsWith (<anonymous>)
    at pathToFileURL (node:internal/url:1474:20)
    at getHandler (C:\Users\Administrator\.code\ccadmin\node_modules\piscina\dist\src\worker.js:62:64)
    at async C:\Users\Administrator\.code\ccadmin\node_modules\piscina\dist\src\worker.js:96:13
```

**Comment by metcoder95** [comment]
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce your issue?
