### ISSUE TITLE
docs: New documentation site

### ISSUE THREAD

**Issue by metcoder95** [jasnell/piscina#557]
It would be great to have improved documentation that can be queriable and ease the experience of understanding Piscina, a couple of more examples and possibly even more advance topics.

[Nx.js](https://nx.dev/getting-started/intro) can be a good inspiration

**Comment by bellatrick** [comment]
Hi @metcoder95, I would love to work on this issue. Do you have a preferred platform for hosting the documentation? Also, are there specific sections that you want to be included or expanded upon?

**Comment by metcoder95** [comment]
Hi @bellatrick!
Not yet, but we are willing to invest in that; so far we are open to suggestions so happy to hear your thoughts.

We can start with something simple, pretty similar to what we have in the ready me but easier to read (maybe some introduction section, examples, API reference, advanced topics, etc.).

I was thinking that we can even port the documentation into a specific `/docs` folder within the repository that hosts all `.md` files and those are parsed into the site.

Let me know if you want me to create a new repo and/or have any thoughts about it. Thanks for volunteering 🙏

**Comment by bellatrick** [comment]
Hey @metcoder95 
Sounds good to me. Docusaurus could be a solid pick for the site. It’s great with Markdown and a search field can easily be added to query sections. Plus, it scales well.

About the repo, a new one could keep things tidy, but it’s really up to you.

**Comment by metcoder95** [comment]
Great! Then let's keep it here, feel free to open a PR to move things forward and let me know how I can be of support

**Comment by bellatrick** [comment]
> Great! Then let's keep it here, feel free to open a PR to move things forward and let me know how I can be of support

Will do 👍
