### ISSUE TITLE
 ReferenceError [Error]: module is not defined in ES module scope

### ISSUE THREAD

**Issue by AlizerUncaged** [jasnell/piscina#586]
for some reason whenever i use ``import ... from`` i get this error 

```bash
node:internal/event_target:1084
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: module is not defined in ES module scope
```

looks like im not able to use es modules for the worker scripts?

**Comment by metcoder95** [comment]
Under which platform are you using Piscina, and which version of Piscina?
Can you also provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?
