### ISSUE TITLE
Using Pino Transports <> Piscina results in extra worker_threads for log transports

### ISSUE THREAD

**Issue by schwers** [jasnell/piscina#601]
I have a project that's now using Piscina and Pino. I am using Piscina for CPU bound work I wanted to get off the main thread -- it works great. I wanted to still use Pino logging in the worker-threads managed by Piscina so that I could get a batching transport.

By default Pino with a transport seems to spin up a new worker-thread transport for each worker_thread in  my Piscina pools. This results in 2X the expected number of worker_threads as each worker in the pool gets a dedicated worker_thread for pino transport.

It should be possible to use tranfserable MessagePorts and some coordination so that all the worker_threads in Pisinca pools can point to the applications main/singula pino transport worker_thread. I tried to implement thisin  "userland" but ran into trouble co-ordinating things. There's a default event listener for messages in the piscina worker wrapper that I accidentally triggered errors for resulting in the worker getting into a bad state.

Would you be open to this style deduplication being a first-class feature? I'm happy to help contribute it with your guidance and suggestions.

**Comment by metcoder95** [comment]
Hmm, can you expand more into what you have in mind to implement within Piscina specifically?
Maybe that will help understand what can be the implications of doing so.

So far, the coordination between threads is already done within Piscina itself. So I'm having a little bit of problem understand what's exactly the attempt
