### ISSUE TITLE
Can you add an example to README as to how to broadcast a message to all worker threads using `BroadcastChannel` (Node v18+)?

### ISSUE THREAD

**Issue by titanism** [jasnell/piscina#615]
Per discussions in [these closed issues](https://github.com/search?q=repo%3Apiscinajs%2Fpiscina+send+message&type=issues), it's clear `piscina` users want to be able to broadcast messages to worker threads.

Could you please add an example to the README as to how to broadcast a message to all threads (and listen in the thread for the message)?

**Comment by metcoder95** [comment]
Closed by #656
