### ISSUE TITLE
Core bug with `piscina.close()` method, which calls `terminate` and `await Promise.all(exitEvents)`

### ISSUE THREAD

**Issue by titanism** [jasnell/piscina#616]
As you can see from screenshot below, upon calling `await piscina.close()`, then `yayaya` does not get emitted, nor do the promises get resolved, and `await Promise.all(exitEvents)` returns early.  This is running from `dist/` folder because of ugly compiled TypeScript.  Using this normally, (e.g. all we do is `new Piscina({ ... })` but we don't run any `piscina.run()` invocations).

<img width="555" alt="Screen Shot 2024-07-18 at 5 29 24 PM" src="https://github.com/user-attachments/assets/9a4f1c08-b5ed-4ef4-9ae8-99524de949b1">

**Comment by titanism** [comment]
The bug is most likely somewhere here <https://github.com/piscinajs/piscina/blob/5169c75a4d744c8503b64f6e5aaac358c4f72e6c/src/index.ts#L573-L584>

**Comment by titanism** [comment]
Not sure exactly what's going on but I think there's definitely a bug somewhere if `calling destroy #4` console log statement above wasn't being executed.

**Comment by metcoder95** [comment]
Can you share an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to support you better?
