### ISSUE TITLE
Feature: Canceling tasks

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#7]
Not all tasks will be cancellable, but it would be nice to have cancellation as an option, either via API or by example to show how it is possible.

**Comment by addaleax** [comment]
The two ways in which we could cancel are 

1. We could cancel pending tasks by just not executing them (this is easy)
2. We could cancel active tasks by terminating the Worker that they are running on, but that only works well when `concurrentTasksPerWorker` has its default value of 1

Another question, what kind of API would we want here? Something like `AbortController` or `AbortSignal`?

**Comment by jasnell** [comment]
Something like AbortController/AbortSignal I think makes the most sense I think... and we'd need to be clear that the semantics are Best Try.
