### ISSUE TITLE
index.d.ts is using invalid type

### ISSUE THREAD

**Issue by savv** [jasnell/piscina#721]
The code in question:
```
export default class Piscina<T = any, R = any> extends EventEmitterAsyncResource {
// ...
    static move(val: Transferable | TransferListItem | ArrayBufferView | ArrayBuffer | MessagePort): ArrayBuffer | 
ArrayBufferView<ArrayBufferLike> |  // HERE
 MessagePort | Transferable;

```

It seems that this code is autogenerated.

The error it causes:
```
node_modules/piscina/dist/index.d.ts:78:116 - error TS2315: Type 'ArrayBufferView' is not generic.

78     static move(val: Transferable | TransferListItem | ArrayBufferView | ArrayBuffer | MessagePort): ArrayBuffer | ArrayBufferView<ArrayBufferLike> | MessagePort | Transferable;
                                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/piscina/dist/index.d.ts:78
```

**Comment by metcoder95** [comment]
Thanks for the report, would you like to send a PR?

**Comment by savv** [comment]
This file (index.d.ts) doesn't exist in the repo; it seems to be generated by gen-esm-wrapper. So I'm a bit unsure how to fix it.

**Comment by metcoder95** [comment]
Hmm, this not from the wrapper but from `tsc` instead; what TS version are you using, I'm not being able to reproduce it locally

**Comment by savv** [comment]
I'm not sure my version of tsc matters (5.1.x). I can see the offending line of code in the unchanged piscina@5.0.0-..alpha. Or are you saying that a newer version of tsc would have supported this?

<img width="863" alt="image" src="https://github.com/user-attachments/assets/1e0786ef-37e8-4ba7-99b9-fa58783b87bc" />

**Comment by savv** [comment]
After cloning piscina and running `./node_modules/typescript/bin/tsc`, I can see that index.d.ts is generated by typescript.

Additionally, I can confirm that lib.es5.d.ts has the appropriate definition:
`interface ArrayBufferView<TArrayBuffer extends ArrayBufferLike = ArrayBufferLike> {`

I guess I'll skipLibChecks for now, and update our TS version later.
