### ISSUE TITLE
Feature: task metrics

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#8]
It would be helpful if metrics were built in.

* Number of pending jobs
* Number of active jobs
* Number of completed jobs
* Job duration histogram
* Idle time histogram

(I will be investigating these)

**Comment by addaleax** [comment]
> Number of pending jobs

Fwiw, that’s currently already exposed as `queueSize`.

**Comment by jasnell** [comment]
Mostly implemented:

1. Pending jobs  ✔
2. Completed jobs  ✔
3. Job duration histogram  ✔
4. Wait time histogram  ✔

Still a few more stats to add.
