### ISSUE TITLE
Piscina vs Cluster

### ISSUE THREAD

**Issue by zscaiosi** [jasnell/piscina#81]
Why and when should I use Piscina instead of Node's Cluster API?
I see there are some nice abstractions but as long as there are issues - when using third party modules - like bundle size, watch for CVEs and vulnerable dependencies etc... I wonder if there is a good reason for using it.

I briefly read the source code and could not figure out when it is a good idea.

Is it safe and advisable to use with expressjs or hapi?

**Comment by jasnell** [comment]
It comes down to a question of when to use threads vs. processes and the answer would typically be to use threads when you need fast communication and shared memory with CPU-intensive tasks. There are several other differences but it really comes down to this. The key issue with the `cluster` API in Node.js has always been with it's sub-optimal API design. @addaleax and I have very briefly discussed the possibility of extending Piscina to support a pool of child processes in addition to worker threads. In theory, it should definitely be possible.

**Comment by jasnell** [comment]
Going to leave this open as a feature request for Piscina to offer a worker child process model. Not sure when we'll be able to get to implementing it but there's no reason why it couldn't work

**Comment by danm** [comment]
Other than the "sub-optimal" API design, what are the downsides to WorkerThreads over processes? 

I have been spinning up processes to handle multiple long CPU intensive tasks but want to try worker threads to avoid the weight of multiple VMs.

**Comment by mceachen** [comment]
> Other than the "sub-optimal" API design, what are the downsides to WorkerThreads over processes?

It really depends on the host OS. 

* Processes are fairly cheap to spawn on posix systems, but take hundreds to thousands (!) of milliseconds to launch on Windows.
* Threads that leak resources can cause the whole process to fail. 
* Child processes can fail spectacularly and not perturb the parent process (other than sending a `SIGCHILD`)

**Comment by nflaig** [comment]
There seems to be very limited information on the performance of `worker_threads` vs `child_process.fork` but benchmarks mentioned in https://github.com/orgs/nodejs/discussions/44264 and [this comment](https://github.com/orgs/nodejs/discussions/44264#discussioncomment-3428883) suggest that a child process might perform better for long running tasks.

We are currently using a `worker_thread` to run our network stack ([libp2p](https://github.com/libp2p/js-libp2p)) off the main thread.

The main goals are
- Move network crypto to thread (CPU intensive)
- Isolate network to protect main thread of DOS attacks
- Allow to throttle network processor better to keep main thread event loop lag under control

But the performance is pretty bad, the network worker is extremely busy, has high event loop lag / high I/O lag. More details and metrics can be found here https://github.com/ChainSafe/lodestar/issues/5604.

The points mentioned in https://github.com/piscinajs/piscina/issues/81#issuecomment-807139880 are great but do not mention any performance considerations besides launch times. I am really curious if there are more benchmarks on this for different type of tasks and if this ultimately just comes down to how the OS manages threads vs processes in terms of resource allocation.

**Comment by metcoder95** [comment]
Maybe I'm missing some part of what you are asking for, but overall it depends on a set of non-deterministic facts that includes your workload and your host machine, its settings etc.

Usually, threads are lightweight but slower. Are perfect for use cases where memory-shared data structures can be used to execute workloads on each thread and coordinate with the main one to load balance such workload.

When using threads you are also often prone to compete with the main thread for CPU time if your main thread does more than only balance the load and also starts executing tasks similar to the threads.

Depending on how much expensive your operations are, you'll decide to use a full fleet of processes instead of a pool of threads that shares smaller chunks of the work.

I do not have any benchmark made on that front, but you can play with it testing different combinations of settings and seeing which one fits better for your problem.

**Comment by nflaig** [comment]
Thanks @metcoder95, this is great information and confirms a lot of the research I had done already on the topic but it was never expressed in such a clear and concise manner.

I will give this a try and post the results here.

> you can play with it testing different combinations of settings

Any specific settings you had in mind? Right now, we are just running a single worker_thread with default settings, it looks like increasing `resourceLimits.maxYoungGenerationSizeMb` improves things a little bit though.

The plan is to use a child_process.fork instead with default settings but can test different setting there as well. Note that the network is very stateful so we cannot use multiple threads/processes to distribute the load.

**Comment by metcoder95** [comment]
>Any specific settings you had in mind? Right now, we are just running a single worker_thread with default settings, it looks like increasing resourceLimits.maxYoungGenerationSizeMb improves things a little bit though.

The `maxYoungGeneration` will enable you to allocate more stuff in the heap that might cause a low number of GC iterations. Have into account that for making it work, most of the objects allocated need to be disposable (free after use). The more hard-reference objects you have, the less impact the `younGenerationSize` will have.

Usually a combination of both `maxYoungGeneration` and `maxOldGeneration` might relieve the need for the GC to run often on the thread, although is not a silver bullet.

You can combine those settings with [Piscina#options](https://github.com/piscinajs/piscina#constructor-new-piscinaoptions) like `minThreads`, `maxThreads`, `idleTimeout`, and `concurrentTaskPerWorker` to tune your setup

**Comment by jdmarshall** [comment]
I’ve been contemplating other architectures for CPU heave Node apps, and the question I wanted to ask today is: what does piscina do if you run it in a worker thread?

That question seems relevant in the context of this thread, because starting child processes in a child process is perfectly doable, and something like piscina could help you deal with failure modes and load balancing.

**Comment by metcoder95** [comment]
Well, it will spawn more threads. It is doable, you'll have good amount of threads fighting for time but sometimes you might want that. Depends on your workload
