### ISSUE TITLE
Accessing the worker threadId?

### ISSUE THREAD

**Issue by robtweed** [jasnell/piscina#82]
Within a worker, is it possible to discover the thread Id?  (ie worker.threadId)

**Comment by jasnell** [comment]
Yes, you can do this just like any other worker in Node.js by using the `threadId` property on the `worker_threads` module:

From within the worker:
```js
const { threadId } = require('worker_threads');
```

Note that this gives you the *Node.js* worker thread ID and not the operating system thread ID.

**Comment by robtweed** [comment]
Perfect - that's exactly what I wanted :-)
