### ISSUE TITLE
Worker State

### ISSUE THREAD

**Issue by Eli-Goldberg** [jasnell/piscina#84]
Hi,
What if a worker has a state, like a db connection that should be open prior to processing,
Should I pass a JS file opens that connection upon being required, and delays processing of any message until that connection is open?

**Comment by jasnell** [comment]
Several bits here...

If there are resources that need to be spun up before the worker is available, then the worker can export an async function. The worker won't be made available to process tasks until the promise is resolved... e.g.

```js
async function init() {
  await initializeWorker();
  return () => { /* This is the worker function */ };
}

module.exports = init();
```

The worker may maintain state but just keep in mind that Piscina could terminate the worker at any time and there's no explicit cleanup that occurs. Take care maintaining any permanent state and make sure that you're accounting for possible abrupt termination.
