### ISSUE TITLE
Warnings about experimental ESM module loader while CommonJS is used

### ISSUE THREAD

**Issue by bhovhannes** [jasnell/piscina#85]
Hi,

I was trying to use Piscina in production and I've used CommonJS for all my code, including worker.

Basically, my worker looks like this:
```javascript
async function initialize() {
    return (action) => {
         // do something cpu-intensive here, based on action received
    }
}
module.exports = initialize();
```

Each time the worker starts, I am getting a message in the console:
```
(node:94710) ExperimentalWarning: The ESM module loader is experimental.
```

That unfortunate, because it is polluting logs and is not in a json format which is the format of my app logger (I use Fastify with Pino).

Is it possible to check is file is written in CommonJS format and use `require` instead of `import` to load worker code?
Or maybe use `require` when file extension is `cjs` (taking into account package type if any?) ?

**Comment by addaleax** [comment]
Right, it is very unfortunate that the warning is logged once the ESM loader is first accessed, not when it’s first *used*.

I *think* just lazy-loading it and switching the priorities (i.e. using `require()` first and `import()` second) might work.

**Comment by bhovhannes** [comment]
@addaleax thank you for handling this!
That was fast!
