### ISSUE TITLE
Order guarantees?

### ISSUE THREAD

**Issue by ronag** [jasnell/piscina#89]
What kind of ordering guarantees does piscina provide? i.e. is it FIFO or whoever finishes first?

**Comment by addaleax** [comment]
https://github.com/piscinajs/piscina#custom-task-queues says:

> By default, Piscina uses a simple array-based first-in-first-out (fifo) task queue. When a new task is submitted and there are no available workers, tasks are pushed on to the queue until a worker becomes available.

If the default fifo queue is not sufficient, user code may replace the task queue implementation with a custom implementation using the `taskQueue` option on the Piscina constructor.

There are no ordering guarantees once the task is passed off to the Worker thread, of course.

**Comment by jasnell** [comment]
@ronag ... take a look at https://github.com/piscinajs/piscina-priority-queue for an example custom task queue that uses a priority queue to determine dispatch order.

**Comment by ronag** [comment]
I was actually more interested in the resolve order, rather than the dispatch order.

**Comment by jasnell** [comment]
Ok, well, as @addaleax points out, there are no guarantees on resolve order. You *could* implement something using SharedArrayBuffer and Atomics but can't really recommend it.

**Comment by ronag** [comment]
What if there is only one worker? Then I guess the order is the same as the dispatch order?

**Comment by jasnell** [comment]
assuming a concurrency of 1, yes. But if the worker is configured to handle more than one task at a time, then that can't be guaranteed
