### ISSUE TITLE
Discuss: runTasks (plural)

### ISSUE THREAD

**Issue by jasnell** [jasnell/piscina#9]
It would be interesting to investigate a variation on the runTask API that allows multiple jobs to be submitted that culminates with a single Promise... using All, Race, and AllSettled semantics... 

e.g.
```js
await piscina.all([ ... tasks])

await piscina.race([... tasks])

await piscina.allSettled([ ... tasks])
```

It would also be interesting to explore the ability to pass in an async generator that can feed tasks to piscina asynchronously ...

```js
piscina.runTasks(my_async_generator)
```

Or ... a stream option

```js
const my_task_transform = ...

stream.pipeline(source, my_task_transform, piscina.stream(), destination, () => {})
```

Really, just thinking about alternative ways of feeding the task queue...

**Comment by addaleax** [comment]
I guess the question here is: Does this actually add value or make the library easier to use? for the `.all`/`.race`/`.settle` variants, it’s fairly straightforward to implement those using the JS built-ins, and developers are already familiar with those anyway.

**Comment by jasnell** [comment]
These would be nice to haves as far as API is concerned. If we don't do convenience APIs for these, let's illustrate how to do it correctly in the examples.

**Comment by addaleax** [comment]
Yeah, I mean, I’ve thought about adding things like support for streams or async iterators, but basically my conclusion was that if you’re using async/await, you’re already doing very fine by using something along the lines of

```js
const results = [];
for await (const task of asyncGenerator())
  results.push(await piscina.runTask(task));
```

**Comment by jasnell** [comment]
A lot of this can be expressed through sample code or docs. The key is just illustrating the easily copyable examples of how to do it correctly and if the pattern of doing it correctly is difficult at all, a convenience API would be helpful (The streams impl might be a good example of the latter)

**Comment by jasnell** [comment]
Closing as a nothing to do here :-)
