### ISSUE TITLE
How to update state of each worker instance

### ISSUE THREAD

**Issue by veedeo** [jasnell/piscina#90]
Lets say each worker has global configuration state, that is same across all workers.
Is it possible to send new configuration object to each Worker to re-initialise its state?

**Comment by jasnell** [comment]
The way to accomplish that would be to set up a per-worker `MessagePort` between the main thread and the worker. There's currently no way of broadcasting to all workers in the pool (although, that may be something we want to try to figure out later @addaleax) so the communication would need to be 1-1 for each worker. The essential idea is that when the configuration change occurs, you'd post a message to the worker via the `MessagePort`. Alternatively, you can pass configuration context as a parameter of a new job for the worker.

**Comment by veedeo** [comment]
My final solution was to initiate a new instance of Piscina, so all further calls of runTask() will go to new instance

**Comment by tuananh** [comment]
> 
> 
> My final solution was to initiate a new instance of Piscina, so all further calls of runTask() will go to new instance

much easier and straight forward :)
