### ISSUE TITLE
Typescript examples of use

### ISSUE THREAD

**Issue by fosk06** [jasnell/piscina#92]
I can't manange to make it work with typescript.
The big problem is the "worker.ts" file, when compiling to "worker.js" file there is no 
`module.exports = ({ a, b }) => {
  return a + b;
};`
In the JS file compiled.
Using `export default function()` in worker.ts file is not working at all.

**Comment by danm** [comment]
I'm confused by this as well. 

my app: 
```
  const piscina = new Piscina({
    filename: path.resolve(__dirname, 'aggregatorFactory/worker.ts'),
  });
```
returns
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"
```

If I change the ts file to js...

```
  const piscina = new Piscina({
    filename: path.resolve(__dirname, 'aggregatorFactory/worker.js'),
  });
```
returns
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 
```

The example in the repo is 
```
const piscina = new Piscina({ filename: __filename });
```
When this transpiles, using ts-node, I'm not sure what directory this uses. 

Can workers be written in Typescript, or do you have to transpile it and use that?

**Comment by fosk06** [comment]
personnally i had no choice to transpile with TS then use the js file wich is not great...

**Comment by jasnell** [comment]
Take a look here for a very simple example: https://github.com/piscinajs/piscina/blob/current/examples/typescript/src/index.ts ... but this cheats a bit in that the worker and the entry point use the same file.

The best approach here is to use a sub-module for the worker. Specifically, you can move your worker.ts into a subfolder with its own package.json file that identifies the appropriate *transpiled* entry point, much the same way you would with the top level package.json. So, something like:

```
index.ts
worker
  worker.ts
  package.json
```

Then, you should be able to reference the worker using the package name instead of the filename:

```
new Worker('worker')
```

Make sure in your typescript configuration the nested package.json gets where it is supposed to go and lists the transpiled worker.js as the entry point target and it should just work.

I'll investigate options for supporting optional runtime transpilation of typescript workers.

**Comment by davidLeonardi** [comment]
Using a transpiled worker is a no-go for me, as it defeats writing in TS and kills the debugging experience.

These guys seem to be doing it right:
https://threads.js.org/usage#type-safe-workers

**Comment by pimartin** [comment]
I managed to make it work in a test/dev environment with ts-node using the following code:
```typescript
// You can use your own logic to test when you want to use TypeScript or not
const isDevOrTest = process.env.TS_NODE_DEV || process.env.NODE_ENV === 'test';

const piscina = new Piscina({
  // In dev or test, we use the .ts file, otherwise, we use the .js file (both have to be beside the current file, watch out for bundlers)
  filename: resolve(__dirname, `./worker${isDevOrTest ? '.ts' : '.js'}`),
  // In dev or test, we register ts-node using nodejs arguments
  execArgv: isDevOrTest ? ['-r', 'ts-node/register'] : undefined,
});
```

The `TS_NODE_DEV` environment variable is set by [ts-node-dev](https://github.com/wclr/ts-node-dev), you will need another logic if you don't use it. For my tests, I use jest with ts-jest.

**Comment by philwingfield** [comment]
I know this is closed but I found the examples didn't meet my use case. I came up with a neat solution based on the above and a couple of other links online:

**workerWrapper.js:**
```
const { workerData } = require('worker_threads');

if (workerData.fullpath.endsWith(".ts")) {
    require('ts-node').register();
}
module.exports = require(workerData.fullpath);

````
**worker.ts:**
```
export const filename = path.resolve(__filename);

export async function doStuff(task: string): Promise<void> {
    // do some stuff
}
```
Then I can in my client code I can pass in the exported filename from worker.ts in the workerdata. This will be .ts in dev and .js in production, meaning that I don't need ts-node in production.

**runner.ts:**
```
import { filename } from "./worker";

const piscina = new Piscina({
            filename: resolve(__dirname, "./workerWrapper.js"),
            workerData: {fullpath: filename }});
...
piscina.run({ task: "string argument to doStuff"}, { name: "doStuff" });
```
Edited to add in case it wasn't clear - you can use the same workerWrapper.js with multiple implementations of worker.ts.
