### ISSUE TITLE
Differentiate different errors, export AbortError

### ISSUE THREAD

**Issue by Prinzhorn** [jasnell/piscina#95]
I might be missing something, but there doesn't seem to be a way to differentiate between an error that happened with the task or an error that happened because it was aborted. Could `AbortError` be exported? So we can do:

```js
try {
  await piscina.runTask(data, abortController);
} catch (err) {
  if(err instanceof AbortError) {
    console.log('The task was canceled');
  } else {
    console.log('The task failed');
  }
}
```

Because I don't need `AbortError` in my logs, they are an expected part of my usage.

**Comment by jasnell** [comment]
We certainly could look at that yes. Likely will be next week at the earliest that I could look unless you wanted to try your hand at a PR :-)

**Comment by Prinzhorn** [comment]
Between my lack of TypeScript skills and not being able import both a default and a named export in commonjs (e.g. `const Piscina, { AbortError } = require('piscina')`) I don't know how to best do this. Adding `AbortError` as a static property to the `Piscina` class seems weird to me. Making `Piscina` a named export is a breaking change. Keeping it as a default and exporting it again as `Piscina` doesn't go very smooth with commonjs (`const Piscina = require('piscina').default`) and is a breaking change as well. I'm probably just overthinking.

**Comment by jasnell** [comment]
Ok, that's fine. I'll work up a few notes on this next week on how it can be done :-)

**Comment by Prinzhorn** [comment]
Thanks!

**Comment by jasnell** [comment]
@Prinzhorn ... #99 should be all that's needed here.

**Comment by Prinzhorn** [comment]
Thanks for looking into that! I was also thinking in a similar direction adding a boolean `aborted` flag to the `AbortError`. I guess this covers 99% of the use-cases. But couldn't a different package have an `AbortError` error as well which could be thrown during the execution of the task itself (during some sort of I/O or whatever). They would be indistinguishable. That's just me being pedantic because that would make for some awkward and hard to track down bugs in this one persons project :smile: 

Now that I think about it, do these errors even travel the thread boundary? I guess they could be properly serialized since `postMessage` uses structured clone algorithm? Or are all errors that occur inside the worker turned into generic `Error` on the caller side when rejecting the promise? In which case this would work fine. I haven't really dug into the piscina code, you can probably answer that from the top of your head.
