### ISSUE TITLE
ParentPort with multiple workers

### ISSUE THREAD

**Issue by pc3b3r** [jasnell/piscina#98]
Is there a way to have a single MessageChannel in the main process with multiple tasks like the [parentPort](https://nodejs.org/api/worker_threads.html#worker_threads_worker_parentport)

I tried with 

```js
(async function () {
  const channel = new MessageChannel()
  channel.port1.on('message', (message) => {
    console.log(message)
  })
  let a = 0
  while (a < 10) {
    piscina.runTask({ hello: `world${a}`, port: channel.port2 }, [channel.port2])
    a++
  }
})()
```

but it gets ```DataCloneError: MessagePort in transfer list is already detached```

**Comment by jasnell** [comment]
`MessageChannel` is one-to-one only and an associated `MessagePort` can only be shared with a single thread. As luck would have it, yesterday I started working on an implementation of `BroadcastChannel` for Node.s: https://github.com/nodejs/node/pull/36271

**Comment by jasnell** [comment]
The PR is getting closer to landing. It's a semver-minor that should be fairly easy to port back to 14.x and 12.x. The way it would work with Piscina is pretty straightforward... your main event loop and your workers would each create their own instances of `new BroadcastChannel('whatever')` where `'whatever'` is some arbitrary shared name. Just keep in mind that any `BroadcastChannel` instance in the entire process could attach to the same channel and also receive the messages, which could be a good thing or bad depending on what you're doing with it.

**Comment by pc3b3r** [comment]
@jasnell thank you for your effort. I look forward to try it asap.
